name: First Workflow
on:
  workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
    - name: Print hallo
      run: echo "Hello world"
    - name: Print daag
      run: echo "Goodbye"
